// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friends.proto

/*
Package friends is a generated protocol buffer package.

It is generated from these files:
	friends.proto

It has these top-level messages:
	Friend
	Ack
	SearchRequest
*/
package friends

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Friend struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Friend) Reset()                    { *m = Friend{} }
func (m *Friend) String() string            { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()               {}
func (*Friend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Friend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Ack struct {
	Ok  bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Ack) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Ack) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SearchRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Friend)(nil), "Friend")
	proto.RegisterType((*Ack)(nil), "Ack")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Friends service

type FriendsClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Friends_SearchClient, error)
	Create(ctx context.Context, opts ...grpc.CallOption) (Friends_CreateClient, error)
}

type friendsClient struct {
	cc *grpc.ClientConn
}

func NewFriendsClient(cc *grpc.ClientConn) FriendsClient {
	return &friendsClient{cc}
}

func (c *friendsClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Friends_SearchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Friends_serviceDesc.Streams[0], c.cc, "/Friends/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &friendsSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Friends_SearchClient interface {
	Recv() (*Friend, error)
	grpc.ClientStream
}

type friendsSearchClient struct {
	grpc.ClientStream
}

func (x *friendsSearchClient) Recv() (*Friend, error) {
	m := new(Friend)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *friendsClient) Create(ctx context.Context, opts ...grpc.CallOption) (Friends_CreateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Friends_serviceDesc.Streams[1], c.cc, "/Friends/Create", opts...)
	if err != nil {
		return nil, err
	}
	x := &friendsCreateClient{stream}
	return x, nil
}

type Friends_CreateClient interface {
	Send(*Friend) error
	CloseAndRecv() (*Ack, error)
	grpc.ClientStream
}

type friendsCreateClient struct {
	grpc.ClientStream
}

func (x *friendsCreateClient) Send(m *Friend) error {
	return x.ClientStream.SendMsg(m)
}

func (x *friendsCreateClient) CloseAndRecv() (*Ack, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Friends service

type FriendsServer interface {
	Search(*SearchRequest, Friends_SearchServer) error
	Create(Friends_CreateServer) error
}

func RegisterFriendsServer(s *grpc.Server, srv FriendsServer) {
	s.RegisterService(&_Friends_serviceDesc, srv)
}

func _Friends_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FriendsServer).Search(m, &friendsSearchServer{stream})
}

type Friends_SearchServer interface {
	Send(*Friend) error
	grpc.ServerStream
}

type friendsSearchServer struct {
	grpc.ServerStream
}

func (x *friendsSearchServer) Send(m *Friend) error {
	return x.ServerStream.SendMsg(m)
}

func _Friends_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FriendsServer).Create(&friendsCreateServer{stream})
}

type Friends_CreateServer interface {
	SendAndClose(*Ack) error
	Recv() (*Friend, error)
	grpc.ServerStream
}

type friendsCreateServer struct {
	grpc.ServerStream
}

func (x *friendsCreateServer) SendAndClose(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *friendsCreateServer) Recv() (*Friend, error) {
	m := new(Friend)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Friends_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Friends",
	HandlerType: (*FriendsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _Friends_Search_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Create",
			Handler:       _Friends_Create_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "friends.proto",
}

func init() { proto.RegisterFile("friends.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2b, 0xca, 0x4c,
	0xcd, 0x4b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe1, 0x62, 0x73, 0x03, 0x0b,
	0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x4a, 0xea, 0x5c, 0xcc, 0x8e, 0xc9, 0xd9, 0x42, 0x7c, 0x5c, 0x4c, 0xf9, 0xd9, 0x60, 0x09,
	0x8e, 0x20, 0xa6, 0xfc, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09, 0x26, 0xb0, 0x4a,
	0x10, 0x53, 0x49, 0x99, 0x8b, 0x37, 0x38, 0x35, 0xb1, 0x28, 0x39, 0x23, 0x28, 0xb5, 0xb0, 0x34,
	0xb5, 0xb8, 0x04, 0x9b, 0x69, 0x46, 0xbe, 0x5c, 0xec, 0x10, 0xbb, 0x8a, 0x85, 0x54, 0xb9, 0xd8,
	0x20, 0xea, 0x85, 0xf8, 0xf4, 0x50, 0x34, 0x4a, 0xb1, 0xeb, 0x41, 0xd4, 0x28, 0x31, 0x18, 0x30,
	0x0a, 0x49, 0x73, 0xb1, 0x39, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x0a, 0xc1, 0x84, 0xa5, 0x58, 0xf4,
	0x1c, 0x93, 0xb3, 0x95, 0x18, 0x34, 0x18, 0x93, 0xd8, 0xc0, 0x3e, 0x30, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xb0, 0x56, 0x79, 0xb0, 0xd2, 0x00, 0x00, 0x00,
}
